'use strict';

/* ------------------------------------------------------------------
 * doodly.io word dictionary - English only.
 * Exactly 1500 words. Minimum 3 letters, maximum 30 characters.
 * ------------------------------------------------------------------ */

var LIST = `
apple,banana,orange,grape,strawberry,blueberry,raspberry,watermelon,pineapple,mango,peach,pear,plum,cherry,
lemon,lime,coconut,kiwi,apricot,fig,papaya,pomegranate,cantaloupe,honeydew,blackberry,cranberry,grapefruit,
tangerine,nectarine,avocado,tomato,potato,carrot,onion,garlic,pepper,cucumber,lettuce,cabbage,broccoli,
cauliflower,spinach,celery,corn,peas,beans,mushroom,pumpkin,zucchini,eggplant,radish,beet,turnip,asparagus,
artichoke,olive,pickle,ginger,chili,squash,bread,toast,bagel,croissant,muffin,donut,pancake,waffle,cereal,
oatmeal,egg,bacon,sausage,ham,steak,chicken,turkey,burger,hotdog,pizza,taco,burrito,sandwich,sub,wrap,salad,
soup,stew,chili dog,noodles,pasta,spaghetti,macaroni,lasagna,ravioli,dumpling,sushi,rice,curry,fries,chips,
popcorn,pretzel,cracker,cookie,brownie,cupcake,cake,pie,tart,pudding,jelly,jam,honey,syrup,butter,cheese,
yogurt,milk,cream,ice cream,milkshake,smoothie,juice,lemonade,soda,water,tea,coffee,hot chocolate,candy,
lollipop,gummy bear,chocolate,marshmallow,cotton candy,caramel,peanut,almond,walnut,cashew,pistachio,
sunflower seed,popsicle,sundae,cone,cheesecake,pancake stack,meatball,sausage roll,omelette,quiche,
pretzel stick,granola,toast rack,jam jar,dog,cat,puppy,kitten,horse,pony,cow,calf,pig,piglet,sheep,lamb,goat,
chicken coop,rooster,hen,duck,duckling,goose,swan,turkey bird,rabbit,bunny,hamster,guinea pig,mouse,rat,
squirrel,chipmunk,beaver,otter,raccoon,skunk,possum,badger,fox,wolf,coyote,bear,panda,polar bear,koala,sloth,
monkey,gorilla,chimpanzee,orangutan,baboon,lemur,lion,tiger,leopard,cheetah,jaguar,panther,lynx,elephant,rhino,
hippo,giraffe,zebra,camel,llama,alpaca,kangaroo,wallaby,deer,elk,moose,reindeer,bison,buffalo,antelope,gazelle,
ibex,yak,donkey,mule,ferret,hedgehog,porcupine,armadillo,anteater,platypus,mole,bat,whale,dolphin,shark,orca,
seal,walrus,sea lion,manatee,narwhal,octopus,squid,jellyfish,starfish,crab,lobster,shrimp,clam,oyster,snail,
slug,seahorse,stingray,eel,swordfish,pufferfish,goldfish,salmon,tuna,catfish,piranha,turtle,tortoise,lizard,
gecko,iguana,chameleon,snake,cobra,python,rattlesnake,crocodile,alligator,dinosaur,frog,toad,tadpole,newt,
salamander,spider,tarantula,scorpion,ant,bee,wasp,hornet,butterfly,moth,caterpillar,dragonfly,ladybug,beetle,
grasshopper,cricket,mantis,firefly,mosquito,fly,worm,centipede,millipede,termite,eagle,hawk,falcon,owl,vulture,
crow,raven,pigeon,dove,sparrow,robin,bluebird,cardinal,finch,canary,parrot,parakeet,macaw,toucan,woodpecker,
hummingbird,flamingo,pelican,seagull,stork,heron,crane,peacock,ostrich,emu,penguin,puffin,kiwi bird,unicorn,
dragon,mermaid,phoenix,griffin,yeti,fairy,elf,gnome,troll,giant,wizard,witch,knight,pirate,ninja,samurai,
cowboy,astronaut,alien,robot,zombie,vampire,werewolf,mummy,ghost,skeleton,monster,superhero,villain,clown,
jester,king,queen,prince,princess,angel,mermaid tail,house,cabin,cottage,mansion,castle,palace,tent,igloo,
treehouse,barn,shed,garage,skyscraper,tower,lighthouse,windmill,bridge,tunnel,church,temple,mosque,pyramid,
museum,library,school,hospital,bank,hotel,restaurant,cafe,bakery,shop,mall,market,factory,farm,stadium,theater,
cinema,circus tent,zoo,aquarium,playground,park,garden,greenhouse,fountain,statue,monument,fence,gate,wall,
roof,chimney,stairs,elevator,escalator,door,window,balcony,porch,driveway,mailbox,street,road,highway,sidewalk,
crosswalk,traffic light,stop sign,streetlight,bench,bus stop,car,truck,bus,van,taxi,ambulance,fire truck,
police car,tractor,bulldozer,crane truck,forklift,dump truck,tow truck,ice cream truck,motorcycle,scooter,
bicycle,unicycle,tricycle,skateboard,rollerblades,wagon,cart,sled,snowmobile,jet ski,boat,canoe,kayak,raft,
sailboat,yacht,ferry,ship,submarine,cruise ship,airplane,jet,helicopter,glider,hot air balloon,blimp,parachute,
rocket,spaceship,satellite,train,subway,tram,monorail,cable car,roller coaster,ferris wheel,carousel,
elevator shaft,anchor,hammer,screwdriver,wrench,pliers,saw,drill,nail,screw,bolt,nut,toolbox,ladder,shovel,
rake,hoe,axe,chainsaw,paintbrush,paint roller,paint can,tape measure,level,clamp,vise,sandpaper,glue,tape,
scissors,knife,fork,spoon,chopsticks,plate,bowl,cup,mug,glass,bottle,jar,can,pot,pan,kettle,teapot,blender,
toaster,microwave,oven,stove,fridge,freezer,dishwasher,sink,faucet,cutting board,rolling pin,whisk,spatula,
ladle,grater,strainer,colander,can opener,corkscrew,napkin,tablecloth,tray,apron,oven mitt,chair,stool,
bench seat,sofa,couch,armchair,recliner,table,desk,bed,bunk bed,crib,cradle,dresser,wardrobe,closet,shelf,
bookcase,cabinet,drawer,mirror,lamp,chandelier,ceiling fan,curtain,blind,rug,carpet,pillow,blanket,quilt,
mattress,clock,alarm clock,hourglass,calendar,picture frame,vase,candle,lantern,flashlight,fireplace,heater,
air conditioner,fan,vacuum,broom,mop,bucket,dustpan,trash can,laundry basket,washing machine,dryer,iron,
ironing board,hanger,clothespin,shirt,tshirt,sweater,hoodie,jacket,coat,raincoat,vest,blazer,suit,tie,bowtie,
scarf,gloves,mittens,hat,cap,beanie,helmet,crown,tiara,pants,jeans,shorts,skirt,dress,gown,pajamas,robe,
swimsuit,socks,shoes,sneakers,boots,sandals,slippers,high heels,flip flops,belt,suspenders,backpack,purse,
wallet,briefcase,suitcase,umbrella,sunglasses,glasses,watch,bracelet,necklace,ring,earring,brooch,pin,button,
zipper,pocket,phone,tablet,laptop,computer,monitor,keyboard,mouse pad,printer,scanner,camera,video camera,
drone,television,remote,radio,speaker,headphones,earbuds,microphone,guitar,electric guitar,bass guitar,violin,
cello,harp,piano,keyboard piano,organ,accordion,banjo,ukulele,mandolin,flute,clarinet,saxophone,trumpet,
trombone,tuba,french horn,harmonica,drum,drum set,cymbal,tambourine,triangle,xylophone,maracas,bongo,bagpipes,
sheet music,music note,metronome,pencil,pen,marker,crayon,chalk,eraser,ruler,protractor,compass,calculator,
notebook,notepad,book,magazine,newspaper,comic book,dictionary,map,globe,atlas,letter,envelope,stamp,postcard,
poster,flag,banner,sign,sticker,badge,ticket,receipt,folder,binder,paper clip,stapler,rubber band,thumbtack,
pushpin,whiteboard,blackboard,easel,canvas,palette,sketchbook,ball,soccer ball,basketball,football,baseball,
tennis ball,golf ball,volleyball,bowling ball,ping pong ball,rugby ball,hockey puck,tennis racket,
badminton racket,golf club,hockey stick,baseball glove,boxing glove,helmet visor,goal post,basketball hoop,net,
whistle,trophy,medal,ribbon,podium,scoreboard,stopwatch,dumbbell,barbell,kettlebell,treadmill,jump rope,
yoga mat,skis,snowboard,surfboard,paddle,skate,ice skate,fishing rod,fishing net,tackle box,bait,hook,tent peg,
sleeping bag,campfire,marshmallow stick,compass needle,binoculars,telescope,microscope,magnet,battery,
light bulb,plug,socket,wire,cable,switch,thermometer,barometer,scale,gear,spring,pulley,lever,wheel,axle,
piston,engine,propeller,turbine,windmill blade,solar panel,antenna,radar,periscope,tree,oak tree,pine tree,
palm tree,willow,maple leaf,leaf,branch,trunk,root,seed,sprout,bush,shrub,hedge,cactus,succulent,fern,moss,
vine,grass,flower,rose,tulip,daisy,sunflower,lily,orchid,daffodil,dandelion,poppy,violet,lavender,carnation,
marigold,bluebell,clover,mushroom cap,acorn,pinecone,log,stump,firewood,forest,jungle,desert,oasis,beach,shore,
island,cliff,mountain,volcano,hill,valley,canyon,cave,waterfall,river,stream,lake,pond,swamp,ocean,wave,tide,
glacier,iceberg,snowman,snowflake,icicle,rainbow,cloud,rain,storm,lightning,thunder,tornado,hurricane,fog,mist,
wind,sun,moon,star,planet,earth,mars,saturn,comet,meteor,galaxy,constellation,eclipse,sunrise,sunset,horizon,
sky,heart,smile,frown,eye,ear,nose,mouth,tooth,tongue,lip,chin,cheek,forehead,eyebrow,eyelash,hair,ponytail,
braid,beard,mustache,head,neck,shoulder,arm,elbow,hand,finger,thumb,fist,palm print,nail polish,leg,knee,foot,
toe,heel,ankle,back,chest,stomach,brain,skull,bone,rib,spine,muscle,lungs,kidney,liver,footprint,handprint,
fingerprint,birthday,party,balloon,confetti,streamer,gift,present,ribbon bow,party hat,pinata,cake candle,
invitation,fireworks,parade,festival,carnival,wedding,honeymoon,anniversary,graduation,diploma,christmas tree,
santa,reindeer sleigh,sleigh,elf hat,ornament,wreath,mistletoe,stocking,gingerbread man,candy cane,snow globe,
menorah,dreidel,easter egg,easter bunny,basket,jack o lantern,halloween mask,costume,broomstick,cauldron,
potion,spell book,magic wand,crystal ball,tarot card,horseshoe,four leaf clover,pot of gold,turkey dinner,
cornucopia,valentine,love letter,cupid,teddy bear,doll,action figure,puppet,marionette,rocking horse,toy car,
toy train,building block,lego brick,puzzle,jigsaw piece,board game,chess,checkers,domino,dice,playing card,
poker chip,marble,yoyo,spinning top,kite,frisbee,slingshot,water gun,bubble wand,bubble,pinwheel,
jack in the box,rubber duck,piggy bank,music box,kaleidoscope,slinky,hula hoop,pogo stick,trampoline,swing,
slide,seesaw,sandbox,monkey bars,merry go round,treasure chest,treasure map,gold coin,jewel,diamond,ruby,
emerald,sapphire,pearl,crown jewel,scepter,goblet,chalice,shield,sword,dagger,spear,bow,arrow,quiver,crossbow,
catapult,cannon,armor,helmet plume,gauntlet,banner flag,drawbridge,moat,dungeon,torch,chain,padlock,key,
keyhole,safe,vault,handcuffs,badge star,siren,megaphone,walkie talkie,radio tower,traffic cone,barrier,
warning sign,first aid kit,bandage,plaster,syringe,pill,medicine bottle,stethoscope,crutch,wheelchair,cast,
thermometer strip,mask,gloves medical,ambulance light,hospital bed,x ray,skeleton hand,tombstone,coffin,
candlestick,cobweb,spider web,haunted house,bats flying,full moon,black cat,scarecrow,hay bale,pitchfork,
wheelbarrow,watering can,flower pot,seed packet,garden hose,sprinkler,lawn mower,leaf blower,birdhouse,
bird feeder,beehive,anthill,nest,egg nest,doghouse,fishbowl,aquarium tank,hamster wheel,leash,collar,
bone treat,dog bowl,cat toy,litter box,saddle,stirrup,horseshoe nail,reins,cowboy hat,lasso,spurs,bandana,
poncho,sombrero,kimono,turban,tiara jewel,monocle,top hat,bow tie clip,cane,pocket watch,typewriter,
fountain pen,ink bottle,quill,scroll,parchment,wax seal,abacus,calculator watch,cash register,shopping cart,
shopping bag,price tag,barcode,coupon,credit card,dollar bill,coin stack,piggy coin,vending machine,
elevator button,escalator step,revolving door,ticket booth,turnstile,bench park,fountain coin,statue base,
gargoyle,column,arch,dome,spire,steeple,weather vane,sundial,flagpole,mailbox flag,letterbox,phone booth,
street vendor,food truck,hot dog cart,ice cream cart,newspaper stand,billboard,neon sign,marquee,curtain stage,
spotlight,microphone stand,drum kit,amplifier,turntable,cassette,vinyl record,compact disc,jukebox,boombox,
karaoke,ticket stub,popcorn bucket,movie reel,clapperboard,film strip,projector,screen,3d glasses,
remote control,game controller,joystick,arcade machine,pinball,slot machine,claw machine,bowling pin,dart,
dartboard,pool table,pool cue,billiard ball,foosball,air hockey,ping pong table,chess board,card deck,
bingo card,jigsaw box,crossword,sudoku,maze,riddle,lightbulb idea,question mark,exclamation mark,arrow sign,
checkmark,cross mark,plus sign,minus sign,peace sign,thumbs up,thumbs down,handshake,high five,wave hello,
clapping,pointing,ok sign,fist bump,heart hands,footsteps,speech bubble,thought bubble,music notes,sparkle,
explosion,splash,smoke,steam,shadow,reflection,silhouette,spiral,zigzag,stripe,polka dot,checkerboard,grid,
triangle shape,square,circle,rectangle,oval,diamond shape,pentagon,hexagon,octagon,star shape,crescent,cube,
sphere,cylinder,cone shape,pyramid shape,prism,knot,ribbon knot,bow knot,braid rope,rope,ladder rope,net rope,
chain link,hook rope,anchor rope,sail,mast,rudder,porthole,life ring,life jacket,scuba tank,snorkel,flippers,
diving mask,harpoon,message bottle,map compass,sextant,spyglass,pirate flag,eye patch,peg leg,parrot shoulder,
treasure key,ship wheel,cannonball,gunpowder barrel,rum bottle,plank,desert island,palm shade,hammock,
beach ball,beach umbrella,sand castle,sand bucket,seashell,starfish sand,crab hole,driftwood,message note,
sunscreen,sunglasses beach,towel,cooler,picnic basket,picnic blanket,barbecue grill,skewer,charcoal,
camping stove,lantern camp,sleeping mat,backpack strap,hiking boot,walking stick,trail sign,mountain flag,
rope bridge,zip line,parachute cord,glider wing,hang glider,skydiver,bungee cord,climbing rope,carabiner,
helmet climb,ice axe,crampon,avalanche,ski lift,snow boots,snow shovel,snow plow,sled ride,ice rink,hockey net,
curling stone,figure skate,ski pole,goggles,snow fort,snowball,frost,frozen lake,penguin slide,polar ice,
northern lights,tent camp,campground,forest path,tree stump seat,mushroom ring,firefly jar,owl branch,
deer trail,bear cave,wolf howl,paw print,animal track,feather,fur,scale fish,shell
`;

var WORDS = LIST.split(',').map((w) => w.trim()).filter(Boolean);

// words for browser
